name: C Build

on:
  push:
    branches: [ main, Development ]
  pull_request:
    branches: [ main, Development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make
      
    - name: Build
      run: make
      
    - name: Check build artifacts
      run: ls -la bin/znak_program
    
    - name: Run the program
      run: ./bin/znak_program < test_input.txt
